apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: image-test-pipeline
  namespace: scc-dev
spec:
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        def imageName = 'test-image'
        def imageTag = 'latest'
        def newImage


        pipeline {
            agent {
                label 'nodejs'
            }

            options {
                timeout(time: 20, unit: 'MINUTES')
            }
            stages {
                stage('test-runner-setup') {
                    steps{
                        script{
                            dir('docker_build') {
                                sh "curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && mkdir -p $HOME/bin && export PATH=$PATH:$HOME/bin && mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test"
                                git url: 'https://gitlab.cee.redhat.com/ebrennan/base-image-testing.git'
                                dir('test_image') {
                                    newImage = docker.build("${imageName}:${imageTag}")
                                    }
                                sh "container-structure-test test --config test_config.yaml --image ${imageName}:${imageTag}"
                                }
                        }
                    }
                    }
                }
            }
    type: JenkinsPipeline
